setwd("C:/Users/User/Documents/PhilippinesR_workshop/CSB/git/sandbox/map")
getwd()
install.packages("maps")
install.packages("mapdata")
install.packages("ggplot2")
install.packages("ggmap")
library(maps)
library(mapdata)
library(ggplot2)
library(ggmap)
m <- map("worldHires", xlim = c(116,127), ylim = c(4,21))
m <- map("worldHires", xlim = c(116,127), ylim = c(4,21), col = "green", fill = T, lwd = 0.5)
map.scale(122,5,relwidth = 0.30, metric = T, ratio = F, cex = 0.6)
map.axes()
